import { useState, type FormEvent } from "react";
import type { ApiEnvironment, ApiRequest, AuthenticationType, BodyType, HttpMethod } from "../../types/apiTesting";
import type { LoadTestPayload, LoadTestProfile, LoadThresholds } from "../../types/loadTesting";
import { AuthEditor } from "../api-testing/AuthEditor";
import { BodyEditor } from "../api-testing/BodyEditor";
import { KeyValueEditor } from "../api-testing/KeyValueEditor";
import { Button } from "../ui/Button";
import { ThresholdEditor } from "./ThresholdEditor";

const emptyThresholds: LoadThresholds = { max_p95_ms: 750, max_p99_ms: 1500, max_failure_rate: 1, max_average_ms: null, min_rps: null, max_error_count: 0 };
const presets: Record<Exclude<LoadTestProfile, "CUSTOM">, Pick<LoadTestPayload, "virtual_users" | "spawn_rate" | "duration_seconds" | "target_rps">> = {
  SMOKE: { virtual_users: 1, spawn_rate: 1, duration_seconds: 30, target_rps: 1 }, BASELINE: { virtual_users: 5, spawn_rate: 1, duration_seconds: 60, target_rps: 5 }, LOAD: { virtual_users: 25, spawn_rate: 5, duration_seconds: 300, target_rps: 50 }, STRESS: { virtual_users: 75, spawn_rate: 10, duration_seconds: 300, target_rps: 150 }, SPIKE: { virtual_users: 100, spawn_rate: 20, duration_seconds: 120, target_rps: 250 }, SOAK: { virtual_users: 20, spawn_rate: 2, duration_seconds: 600, target_rps: 30 },
};

export function newLoadTest(environmentId = ""): LoadTestPayload {
  return { name: "", description: "", api_request_id: null, environment_id: environmentId, target_url: "", request_method: "GET", headers: [], query_parameters: [], body: "", body_type: "NONE", authentication_type: "NONE", authentication_config: {}, profile: "CUSTOM", virtual_users: 10, spawn_rate: 2, duration_seconds: 30, timeout_seconds: 10, target_rps: null, thresholds: emptyThresholds };
}

export function LoadTestForm({ initial, environments, requests, busy, onSubmit, onCancel }: { initial: LoadTestPayload; environments: ApiEnvironment[]; requests: ApiRequest[]; busy: boolean; onSubmit: (payload: LoadTestPayload) => void; onCancel: () => void }) {
  const [value, setValue] = useState(initial); const [tab, setTab] = useState<"request" | "auth" | "body" | "thresholds">("request");
  const patch = (next: Partial<LoadTestPayload>) => setValue((current) => ({ ...current, ...next }));
  function profile(profileValue: LoadTestProfile) { patch({ profile: profileValue, ...(profileValue === "CUSTOM" ? {} : presets[profileValue]) }); }
  function source(requestId: string) { const request = requests.find((item) => item.id === requestId); if (!request) { patch({ api_request_id: null }); return; } patch({ api_request_id: request.id, name: value.name || `${request.name} load test`, target_url: request.url, request_method: request.method, headers: request.headers, query_parameters: request.query_parameters, body: request.body, body_type: request.body_type, authentication_type: request.authentication_type, authentication_config: request.authentication_config }); }
  function submit(event: FormEvent) { event.preventDefault(); onSubmit({ ...value, name: value.name.trim(), target_url: value.target_url.trim() }); }
  return <form className="load-test-form" onSubmit={submit}>
    <div className="form-grid"><label className="field"><span>Name</span><input required value={value.name} onChange={(event) => patch({ name: event.target.value })} /></label><label className="field"><span>Profile</span><select value={value.profile} onChange={(event) => profile(event.target.value as LoadTestProfile)}>{["CUSTOM", ...Object.keys(presets)].map((item) => <option key={item}>{item}</option>)}</select></label></div>
    <label className="field"><span>Description</span><textarea rows={2} value={value.description ?? ""} onChange={(event) => patch({ description: event.target.value })} /></label>
    <div className="form-grid"><label className="field"><span>Environment</span><select required value={value.environment_id} onChange={(event) => patch({ environment_id: event.target.value })}><option value="">Select environment</option>{environments.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.classification})</option>)}</select></label><label className="field"><span>Reuse API request (optional)</span><select value={value.api_request_id ?? ""} onChange={(event) => source(event.target.value)}><option value="">Standalone request</option>{requests.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
    <div className="request-line load-target-line"><select aria-label="HTTP method" className="method-select" value={value.request_method} onChange={(event) => patch({ request_method: event.target.value as HttpMethod })}>{["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"].map((item) => <option key={item}>{item}</option>)}</select><input aria-label="Target URL" required type="url" value={value.target_url} onChange={(event) => patch({ target_url: event.target.value })} placeholder="https://qa.example.com/api/health" /></div>
    <div className="form-grid load-config-grid"><label className="field"><span>Virtual users</span><input required type="number" min="1" value={value.virtual_users} onChange={(e) => patch({ virtual_users: Number(e.target.value) })} /></label><label className="field"><span>Spawn rate / second</span><input required type="number" min="0.1" step="0.1" value={value.spawn_rate} onChange={(e) => patch({ spawn_rate: Number(e.target.value) })} /></label><label className="field"><span>Duration (seconds)</span><input required type="number" min="1" value={value.duration_seconds} onChange={(e) => patch({ duration_seconds: Number(e.target.value) })} /></label><label className="field"><span>Request timeout (seconds)</span><input required type="number" min="0.1" step="0.1" value={value.timeout_seconds} onChange={(e) => patch({ timeout_seconds: Number(e.target.value) })} /></label><label className="field"><span>Target RPS (optional)</span><input type="number" min="0.1" step="0.1" value={value.target_rps ?? ""} onChange={(e) => patch({ target_rps: e.target.value ? Number(e.target.value) : null })} /></label></div>
    <div className="api-tabs">{(["request", "auth", "body", "thresholds"] as const).map((item) => <button type="button" className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</div>
    <div className="request-editor-panel">{tab === "request" && <><h4>Headers</h4><KeyValueEditor items={value.headers} onChange={(headers) => patch({ headers })} /><h4>Query parameters</h4><KeyValueEditor items={value.query_parameters} onChange={(query_parameters) => patch({ query_parameters })} /></>}{tab === "auth" && <AuthEditor type={value.authentication_type} config={value.authentication_config} onType={(authentication_type: AuthenticationType) => patch({ authentication_type })} onConfig={(authentication_config) => patch({ authentication_config })} />}{tab === "body" && <BodyEditor type={value.body_type} body={value.body ?? ""} onType={(body_type: BodyType) => patch({ body_type })} onBody={(body) => patch({ body })} />}{tab === "thresholds" && <ThresholdEditor value={value.thresholds} onChange={(thresholds) => patch({ thresholds })} />}</div>
    <div className="alert load-safety-note">Targets must use HTTP(S), pass DNS/IP safety checks, and match the server and project allowlists. Production requires an administrator and explicit confirmation.</div>
    <div className="modal-actions"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" isLoading={busy}>Save load test</Button></div>
  </form>;
}
