import type { AutomationAssertion, AutomationCondition } from "../../types/automation";
import { Button } from "../ui/Button";

export function AutomationAssertionEditor({ value, onChange }: { value: AutomationAssertion[]; onChange: (value: AutomationAssertion[]) => void }) {
  function change(index: number, patch: Partial<AutomationAssertion>) { onChange(value.map((item, i) => i === index ? { ...item, ...patch } : item)); }
  return <div><p className="muted">Assertions inspect the most recent response in this test case.</p>{value.map((item, i) => <fieldset className="automation-assertion" key={i}><legend>Assertion {i + 1}</legend><div className="form-grid"><label className="field">Source<select value={item.source} onChange={(e) => change(i, { source: e.target.value as AutomationAssertion["source"] })}>{["STATUS_CODE", "BODY", "JSON_PATH", "HEADER", "RESPONSE_TIME"].map((source) => <option key={source}>{source}</option>)}</select></label><label className="field">Operator<select value={item.operator} onChange={(e) => change(i, { operator: e.target.value as AutomationAssertion["operator"] })}>{["EQUALS", "NOT_EQUALS", "GREATER_THAN", "LESS_THAN", "CONTAINS", "NOT_CONTAINS", "EXISTS"].map((operator) => <option key={operator}>{operator}</option>)}</select></label>{["JSON_PATH", "HEADER"].includes(item.source) && <label className="field">Target<input required value={item.target ?? ""} placeholder={item.source === "JSON_PATH" ? "$.data.id" : "Content-Type"} onChange={(e) => change(i, { target: e.target.value })} /></label>}{item.operator !== "EXISTS" && <label className="field">Expected<input required value={item.expected ?? ""} onChange={(e) => change(i, { expected: e.target.value })} /></label>}</div><Button type="button" variant="ghost" onClick={() => onChange(value.filter((_, index) => index !== i))}>Remove assertion {i + 1}</Button></fieldset>)}<Button type="button" variant="secondary" onClick={() => onChange([...value, { source: "STATUS_CODE", operator: "EQUALS", expected: "200" }])}>Add assertion</Button></div>;
}
export const DEFAULT_CONDITION: AutomationCondition = { source: "STATUS_CODE", operator: "EQUALS", expected: "200" };
export function ConditionEditor({ value, onChange }: { value: AutomationCondition; onChange: (value: AutomationCondition) => void }) {
  return <div className="form-grid"><label className="field">Condition source<select value={value.source} onChange={(e) => onChange({ ...value, source: e.target.value as AutomationCondition["source"] })}>{["STATUS_CODE", "VARIABLE", "JSON_PATH", "HEADER"].map((source) => <option key={source}>{source}</option>)}</select></label><label className="field">Condition operator<select value={value.operator} onChange={(e) => onChange({ ...value, operator: e.target.value as AutomationCondition["operator"] })}>{["EQUALS", "NOT_EQUALS", "CONTAINS", "EXISTS"].map((operator) => <option key={operator}>{operator}</option>)}</select></label>{value.source !== "STATUS_CODE" && <label className="field">Condition target<input required value={value.target ?? ""} onChange={(e) => onChange({ ...value, target: e.target.value })} placeholder={value.source === "VARIABLE" ? "user_id" : "$.data.id"} /></label>}{value.operator !== "EXISTS" && <label className="field">Condition expected<input value={value.expected ?? ""} onChange={(e) => onChange({ ...value, expected: e.target.value })} /></label>}</div>;
}
