import { useState, type FormEvent } from "react";
import { extractErrorMessage } from "../../api/client";
import type { ApiEnvironment } from "../../types/apiTesting";
import type { SuitePayload } from "../../types/automation";
import { Button } from "../ui/Button";
import { Modal } from "../ui/Modal";
import { AutomationError } from "./AutomationShared";

export function SuiteForm({ initial, environments, onSave, onClose }: { initial?: SuitePayload; environments: ApiEnvironment[]; onSave: (payload: SuitePayload) => Promise<void>; onClose: () => void }) {
  const [form, setForm] = useState<SuitePayload>(initial ?? { name: "", description: "", environment_id: null, status: "DRAFT", auto_create_bugs: false, max_retries: 0, allowed_hosts: [] });
  const [hosts, setHosts] = useState(initial?.allowed_hosts.join("\n") ?? ""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { await onSave({ ...form, allowed_hosts: hosts.split(/[\n,]/).map((item) => item.trim()).filter(Boolean) }); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setBusy(false); } }
  return <Modal wide title={initial ? "Suite settings" : "Create automation suite"} onClose={() => !busy && onClose()}><form onSubmit={save}>{error && <AutomationError message={error} />}<label className="field">Suite name<input required maxLength={255} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="field">Description<textarea rows={3} value={form.description ?? ""} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="form-grid"><label className="field">Default environment<select value={form.environment_id ?? ""} onChange={(e) => setForm({ ...form, environment_id: e.target.value || null })}><option value="">No environment</option>{environments.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.classification})</option>)}</select></label><label className="field">Suite status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as SuitePayload["status"] })}>{["DRAFT", "ACTIVE", "DISABLED", "ARCHIVED"].map((status) => <option key={status}>{status}</option>)}</select></label></div><label className="field">Maximum retries<input type="number" min={0} max={3} required value={form.max_retries} onChange={(e) => setForm({ ...form, max_retries: Number(e.target.value) })} /><small>Failed steps may retry. Invalid configuration and authentication configuration errors are never retried.</small></label><label className="field">Allowed target hosts<textarea rows={3} value={hosts} onChange={(e) => setHosts(e.target.value)} placeholder={"api.example.com\n*.qa.example.com"} /><small>One hostname per line. Configure authorized hosts before running the suite.</small></label><label className="checkbox-field"><input type="checkbox" checked={form.auto_create_bugs} onChange={(e) => setForm({ ...form, auto_create_bugs: e.target.checked })} />Create bugs automatically for final failures</label><p className="muted">An existing unresolved bug for the same failure is reused.</p><div className="modal-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" isLoading={busy}>Save suite</Button></div></form></Modal>;
}
