import { useState } from "react";
import type { ApiEnvironment, EnvironmentVariable } from "../../types/apiTesting";
import { createApiEnvironment, deleteApiEnvironment, updateApiEnvironment } from "../../api/apiTesting";
import { extractErrorMessage } from "../../api/client";
import { useToast } from "../../context/ToastContext";
import { Button } from "../ui/Button";
import { Modal } from "../ui/Modal";

export function EnvironmentManager({ projectId, environments, onClose, onChanged }: { projectId: string; environments: ApiEnvironment[]; onClose: () => void; onChanged: () => void }) {
  const [selected, setSelected] = useState<ApiEnvironment | null>(environments[0] ?? null); const [name, setName] = useState(selected?.name ?? ""); const [classification, setClassification] = useState<ApiEnvironment["classification"]>(selected?.classification ?? "QA"); const [variables, setVariables] = useState<EnvironmentVariable[]>(selected?.variables ?? []); const [saving, setSaving] = useState(false); const { showToast } = useToast();
  function choose(id: string) { const item = environments.find((env) => env.id === id) ?? null; setSelected(item); setName(item?.name ?? ""); setClassification(item?.classification ?? "QA"); setVariables(item?.variables ?? []); }
  function updateVariable(index: number, patch: Partial<EnvironmentVariable>) { setVariables((items) => items.map((item, i) => i === index ? { ...item, ...patch } : item)); }
  async function save() { if (!name.trim()) return; setSaving(true); try { if (selected) await updateApiEnvironment(selected.id, { name, classification, variables }); else await createApiEnvironment(projectId, { name, classification, variables }); showToast("Environment saved.", "success"); onChanged(); } catch (error) { showToast(extractErrorMessage(error), "error"); } finally { setSaving(false); } }
  async function remove() { if (!selected || !window.confirm(`Delete ${selected.name}?`)) return; try { await deleteApiEnvironment(selected.id); showToast("Environment deleted.", "success"); onChanged(); choose(""); } catch (error) { showToast(extractErrorMessage(error), "error"); } }
  return <Modal wide title="API Environments" onClose={onClose}><div className="environment-manager"><aside><Button onClick={() => choose("")}>+ New</Button>{environments.map((item) => <button className={selected?.id === item.id ? "active" : ""} onClick={() => choose(item.id)} key={item.id}>{item.name} <small>{item.classification}</small></button>)}</aside><div><div className="form-grid"><label className="field"><span>Name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="QA" /></label><label className="field"><span>Classification</span><select value={classification} onChange={(e) => setClassification(e.target.value as ApiEnvironment["classification"])}>{["DEVELOPMENT", "TEST", "QA", "STAGING", "PRODUCTION"].map((item) => <option key={item}>{item}</option>)}</select></label></div>{classification === "PRODUCTION" && <div className="alert alert-error">Production load tests are disabled by default and require explicit administrator confirmation.</div>}<h3>Variables</h3>{variables.map((item, index) => <div className="variable-row" key={index}><input placeholder="name" value={item.name} onChange={(e) => updateVariable(index, { name: e.target.value })} /><input type={item.is_secret ? "password" : "text"} placeholder="value" value={item.value} onChange={(e) => updateVariable(index, { value: e.target.value })} /><label><input type="checkbox" checked={item.is_secret} onChange={(e) => updateVariable(index, { is_secret: e.target.checked })} /> Secret</label><button type="button" className="icon-button" onClick={() => setVariables(variables.filter((_, i) => i !== index))}>×</button></div>)}<button type="button" className="inline-link" onClick={() => setVariables([...variables, { name: "", value: "", is_secret: false }])}>+ Add variable</button><div className="modal-actions">{selected && <Button variant="danger" onClick={remove}>Delete</Button>}<Button variant="secondary" onClick={onClose}>Close</Button><Button isLoading={saving} onClick={save}>Save</Button></div></div></div></Modal>;
}
