import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { createAutomationCase, createAutomationStep, deleteAutomationCase, deleteAutomationStep, deleteAutomationSuite, getAutomationSuite, reorderAutomationCases, reorderAutomationSteps, updateAutomationCase, updateAutomationStep, updateAutomationSuite } from "../api/automation";
import { getApiCollection, listApiCollections, listApiEnvironments } from "../api/apiTesting";
import { extractErrorMessage } from "../api/client";
import { AutomationBadge, AutomationError } from "../components/automation/AutomationShared";
import { RunSuiteModal } from "../components/automation/RunSuiteModal";
import { STEP_LABELS, StepEditor, newStep } from "../components/automation/StepEditor";
import { SuiteForm } from "../components/automation/SuiteForm";
import { AppLayout } from "../components/layout/AppLayout";
import { Button } from "../components/ui/Button";
import { LoadingSpinner } from "../components/ui/LoadingSpinner";
import { Modal } from "../components/ui/Modal";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import type { ApiEnvironment, ApiRequest } from "../types/apiTesting";
import type { AutomationCase, AutomationStep, AutomationSuite, CasePayload, StepPayload } from "../types/automation";

function moved(ids: string[], index: number, delta: number) { const copy = [...ids]; [copy[index], copy[index + delta]] = [copy[index + delta], copy[index]]; return copy; }
export function AutomationSuiteBuilder() {
  const { projectId = "", suiteId = "" } = useParams(); const { user } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate();
  const [suite, setSuite] = useState<AutomationSuite | null>(null); const [environments, setEnvironments] = useState<ApiEnvironment[]>([]); const [requests, setRequests] = useState<ApiRequest[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [settings, setSettings] = useState(false); const [run, setRun] = useState(false); const [caseEditor, setCaseEditor] = useState<AutomationCase | "new" | null>(null); const [stepEditor, setStepEditor] = useState<{ caseId: string; step?: AutomationStep; initial: StepPayload } | null>(null);
  const canManage = user?.role === "ADMIN" || user?.role === "QA_ENGINEER";
  const refresh = useCallback(async () => { const { data } = await getAutomationSuite(suiteId); setSuite(data); }, [suiteId]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [suiteResponse, envResponse, collections] = await Promise.all([getAutomationSuite(suiteId), listApiEnvironments(projectId), listApiCollections(projectId)]); setSuite(suiteResponse.data); setEnvironments(envResponse.data); const details = await Promise.all(collections.data.map((collection) => getApiCollection(collection.id))); setRequests(details.flatMap((response) => response.data.requests ?? [])); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setLoading(false); } }, [projectId, suiteId]);
  useEffect(() => { void load(); }, [load]);
  async function mutate(action: () => Promise<unknown>, message: string) { setBusy(true); setError(""); try { await action(); await refresh(); showToast(message, "success"); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setBusy(false); } }
  async function saveCase(payload: CasePayload) { if (caseEditor === "new") await createAutomationCase(suiteId, payload); else if (caseEditor) await updateAutomationCase(caseEditor.id, payload); await refresh(); setCaseEditor(null); showToast("Test case saved.", "success"); }
  async function saveStep(payload: StepPayload) { if (!stepEditor) return; if (stepEditor.step) await updateAutomationStep(stepEditor.step.id, payload); else await createAutomationStep(stepEditor.caseId, payload); await refresh(); setStepEditor(null); showToast("Workflow step saved.", "success"); }
  async function duplicateStep(testCase: AutomationCase, step: AutomationStep) { const { name, step_type, enabled, api_request_id, config, condition } = step; await mutate(() => createAutomationStep(testCase.id, { name: `${name} (copy)`, step_type, order_index: testCase.steps.length, enabled, api_request_id, config, condition }), "Step duplicated. Review secret configuration before execution."); }
  const cases = [...(suite?.cases ?? [])].sort((a, b) => a.order_index - b.order_index);
  return <AppLayout><Link className="bug-breadcrumb" to={`/projects/${projectId}/automation`}>← Automation</Link>{error && <AutomationError message={error} retry={load} />}{loading ? <LoadingSpinner /> : suite && <><div className="page-header"><div><h1>{suite.name}</h1><AutomationBadge status={suite.status} /><p className="muted">{suite.description || "Build an ordered workflow from reusable requests and checks."}</p></div>{canManage && <div className="page-actions"><Button variant="secondary" disabled={busy} onClick={() => setSettings(true)}>Suite settings</Button><Button variant="secondary" disabled={busy} onClick={() => setCaseEditor("new")}>Add test case</Button><Button disabled={busy || !cases.length || ["DISABLED", "ARCHIVED"].includes(suite.status)} onClick={() => setRun(true)}>Run suite</Button></div>}</div>
    <section className="panel automation-suite-summary"><span>Environment: <strong>{environments.find((item) => item.id === suite.environment_id)?.name ?? "None"}</strong></span><span>{suite.max_retries} retries</span><span>Automatic bugs: {suite.auto_create_bugs ? "On" : "Off"}</span><Link to={`/projects/${projectId}/automation/runs?suite_id=${suite.id}`}>Run history</Link></section>
    {!canManage && <p className="muted">You have read-only access to this automation suite.</p>}
    {!cases.length && <section className="panel empty-state"><h2>Your workflow starts with a test case</h2><p>Group related actions, then add requests, assertions, and extraction steps.</p>{canManage && <Button onClick={() => setCaseEditor("new")}>Add test case</Button>}</section>}
    {cases.map((testCase, caseIndex) => <section key={testCase.id} className={`panel automation-case${testCase.enabled ? "" : " automation-disabled"}`}><div className="panel-header"><div><small className="muted">CASE {caseIndex + 1} · {testCase.timeout}s timeout</small><h2>{testCase.name}</h2>{testCase.description && <p className="muted">{testCase.description}</p>}</div>{canManage && <div className="button-row"><label className="checkbox-field"><input aria-label={`Enable case ${testCase.name}`} type="checkbox" checked={testCase.enabled} disabled={busy} onChange={(e) => void mutate(() => updateAutomationCase(testCase.id, { enabled: e.target.checked }), "Case updated.")} />Enabled</label><Button variant="ghost" disabled={busy || caseIndex === 0} aria-label={`Move case ${testCase.name} up`} onClick={() => void mutate(() => reorderAutomationCases(suiteId, moved(cases.map((item) => item.id), caseIndex, -1)), "Cases reordered.")}>↑</Button><Button variant="ghost" disabled={busy || caseIndex === cases.length - 1} aria-label={`Move case ${testCase.name} down`} onClick={() => void mutate(() => reorderAutomationCases(suiteId, moved(cases.map((item) => item.id), caseIndex, 1)), "Cases reordered.")}>↓</Button><Button variant="secondary" disabled={busy} onClick={() => setCaseEditor(testCase)}>Edit case</Button><Button variant="ghost" disabled={busy} onClick={() => { if (window.confirm(`Delete test case "${testCase.name}" and its steps?`)) void mutate(() => deleteAutomationCase(testCase.id), "Case removed."); }}>Remove case</Button></div>}</div>
    <ol className="automation-workflow">{[...testCase.steps].sort((a, b) => a.order_index - b.order_index).map((step, stepIndex, orderedSteps) => <li key={step.id} className={step.enabled ? "" : "automation-disabled"}><span className="automation-step-number">{stepIndex + 1}</span><div className="automation-step-content"><span className="automation-step-kind">{STEP_LABELS[step.step_type]}</span><strong>{step.name}</strong>{step.step_type === "HTTP_REQUEST" && <code>{step.api_request_id ? `Saved request: ${requests.find((item) => item.id === step.api_request_id)?.name ?? "Linked API request"}` : `${step.config.request?.method ?? "GET"} ${step.config.request?.url ?? ""}`}</code>}{step.condition && <small className="muted">Conditional · {step.condition.source} {step.condition.operator}</small>}</div>{canManage && <div className="automation-step-actions"><label title="Enable step"><input type="checkbox" aria-label={`Enable step ${step.name}`} checked={step.enabled} disabled={busy} onChange={(e) => void mutate(() => updateAutomationStep(step.id, { enabled: e.target.checked }), "Step updated.")} /></label><Button variant="ghost" disabled={busy || stepIndex === 0} aria-label={`Move ${step.name} up`} onClick={() => void mutate(() => reorderAutomationSteps(testCase.id, moved(orderedSteps.map((item) => item.id), stepIndex, -1)), "Steps reordered.")}>↑</Button><Button variant="ghost" disabled={busy || stepIndex === orderedSteps.length - 1} aria-label={`Move ${step.name} down`} onClick={() => void mutate(() => reorderAutomationSteps(testCase.id, moved(orderedSteps.map((item) => item.id), stepIndex, 1)), "Steps reordered.")}>↓</Button><Button variant="secondary" disabled={busy} onClick={() => setStepEditor({ caseId: testCase.id, step, initial: step })}>Configure</Button><Button variant="ghost" disabled={busy} aria-label={`Duplicate ${step.name}`} onClick={() => void duplicateStep(testCase, step)}>Duplicate</Button><Button variant="ghost" disabled={busy} aria-label={`Remove ${step.name}`} onClick={() => { if (window.confirm(`Remove step "${step.name}"?`)) void mutate(() => deleteAutomationStep(step.id), "Step removed."); }}>Remove</Button></div>}</li>)}</ol>{!testCase.steps.length && <p className="muted">No steps yet. Add the first request to this case.</p>}{canManage && <Button variant="secondary" disabled={busy} onClick={() => setStepEditor({ caseId: testCase.id, initial: newStep("HTTP_REQUEST", testCase.steps.length) })}>Add step</Button>}</section>)}
    {canManage && <div className="automation-delete-suite"><Button variant="ghost" disabled={busy} onClick={async () => { if (!window.confirm(`Delete suite "${suite.name}"? Run history will be retained.`)) return; setBusy(true); try { await deleteAutomationSuite(suiteId); showToast("Suite removed.", "success"); navigate(`/projects/${projectId}/automation`); } catch (reason) { setError(extractErrorMessage(reason)); setBusy(false); } }}>Delete suite</Button></div>}
    {settings && <SuiteForm initial={suite} environments={environments} onClose={() => setSettings(false)} onSave={async (payload) => { await updateAutomationSuite(suiteId, payload); await refresh(); setSettings(false); showToast("Suite settings saved.", "success"); }} />}{run && <RunSuiteModal suite={suite} environments={environments} onClose={() => setRun(false)} />}{caseEditor && <CaseEditor initial={caseEditor === "new" ? { name: "", description: "", enabled: true, timeout: 60, order_index: cases.length } : caseEditor} onSave={saveCase} onClose={() => setCaseEditor(null)} />}{stepEditor && <StepEditor initial={stepEditor.initial} requests={requests} onSave={saveStep} onClose={() => setStepEditor(null)} />}
    </>}</AppLayout>;
}

function CaseEditor({ initial, onSave, onClose }: { initial: CasePayload; onSave: (payload: CasePayload) => Promise<void>; onClose: () => void }) {
  const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await onSave(form); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setBusy(false); } }
  return <Modal title="Test case" onClose={() => !busy && onClose()}><form onSubmit={save}>{error && <AutomationError message={error} />}<label className="field">Case name<input required maxLength={255} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="field">Description<textarea value={form.description ?? ""} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="field">Case timeout (seconds)<input type="number" min={1} max={3600} required value={form.timeout} onChange={(e) => setForm({ ...form, timeout: Number(e.target.value) })} /></label><label className="checkbox-field"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} />Case enabled</label><div className="modal-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" isLoading={busy}>Save case</Button></div></form></Modal>;
}
