import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { createAutomationSuite, getAutomationStatistics, listAutomationSchedules, listAutomationSuites } from "../api/automation";
import { listApiEnvironments } from "../api/apiTesting";
import { extractErrorMessage } from "../api/client";
import { AutomationBadge, AutomationError, AutomationNav, AutomationPagination, AutomationRunTable } from "../components/automation/AutomationShared";
import { SuiteForm } from "../components/automation/SuiteForm";
import { AppLayout } from "../components/layout/AppLayout";
import { Button } from "../components/ui/Button";
import { LoadingSpinner } from "../components/ui/LoadingSpinner";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import type { ApiEnvironment } from "../types/apiTesting";
import type { AutomationPage, AutomationSchedule, AutomationStatistics, AutomationSuite, RunFilters, SuitePayload } from "../types/automation";

export function Automation() {
  const { projectId = "" } = useParams(); const { user } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate();
  const [suites, setSuites] = useState<AutomationPage<AutomationSuite> | null>(null); const [statistics, setStatistics] = useState<AutomationStatistics | null>(null); const [schedules, setSchedules] = useState<AutomationSchedule[]>([]); const [environments, setEnvironments] = useState<ApiEnvironment[]>([]);
  const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [creating, setCreating] = useState(false);
  const [filters, setFilters] = useState<RunFilters>({});
  const canManage = user?.role === "ADMIN" || user?.role === "QA_ENGINEER";
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [suiteResponse, statResponse, scheduleResponse, envResponse] = await Promise.all([listAutomationSuites(projectId, page), getAutomationStatistics(projectId, filters), listAutomationSchedules(projectId), listApiEnvironments(projectId)]); setSuites(suiteResponse.data); setStatistics(statResponse.data); setSchedules(scheduleResponse.data.items); setEnvironments(envResponse.data); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setLoading(false); } }, [projectId, page, filters]);
  useEffect(() => { void load(); }, [load]);
  async function create(payload: SuitePayload) { const { data } = await createAutomationSuite(projectId, payload); showToast("Suite created. Add your first test case.", "success"); navigate(`/projects/${projectId}/automation/suites/${data.id}`); }
  const largestFailure = Math.max(1, ...(statistics?.failed_trends.map((item) => item.count) ?? []));
  const changeFilter = (key: keyof RunFilters, value: string) => setFilters((current) => ({ ...current, [key]: value || undefined }));
  return <AppLayout><div className="page-header"><div><h1>Automation</h1><p className="muted">Reusable API workflows, scheduled checks, and actionable results.</p></div>{canManage && <Button onClick={() => setCreating(true)}>Create suite</Button>}</div><AutomationNav projectId={projectId} />{error && <AutomationError message={error} retry={load} />}{loading ? <LoadingSpinner /> : statistics && suites && <>
    <section className="panel automation-run-filters" aria-label="Dashboard filters"><label className="field">Suite<select value={filters.suite_id ?? ""} onChange={(e) => changeFilter("suite_id", e.target.value)}><option value="">All suites</option>{suites.items.map((suite) => <option key={suite.id} value={suite.id}>{suite.name}</option>)}</select></label><label className="field">Environment<select value={filters.environment_id ?? ""} onChange={(e) => changeFilter("environment_id", e.target.value)}><option value="">All environments</option>{environments.map((environment) => <option key={environment.id} value={environment.id}>{environment.name}</option>)}</select></label><label className="field">Status<select value={filters.status ?? ""} onChange={(e) => changeFilter("status", e.target.value)}><option value="">All statuses</option>{["QUEUED", "RUNNING", "PASSED", "FAILED", "CANCELLED"].map((status) => <option key={status}>{status}</option>)}</select></label><label className="field">From date<input type="date" value={filters.created_from ?? ""} onChange={(e) => changeFilter("created_from", e.target.value)} /></label><label className="field">To date<input type="date" min={filters.created_from ?? ""} value={filters.created_to ?? ""} onChange={(e) => changeFilter("created_to", e.target.value)} /></label></section>
    <section className="automation-stat-grid" aria-label="Automation statistics">{[["Total suites", statistics.total_suites], ["Active schedules", statistics.active_schedules], ["Total runs", statistics.total_runs], ["Pass rate", `${statistics.pass_rate.toFixed(1)}%`], ["Failure rate", `${statistics.failure_rate.toFixed(1)}%`], ["Average duration", `${(statistics.average_duration_ms / 1000).toFixed(1)}s`]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <section className="panel"><div className="panel-header"><h2>Test suites</h2><span className="muted">{suites.total} suites</span></div>{!suites.items.length ? <div className="empty-state"><h3>Build your first workflow</h3><p>Chain requests, extract variables, and verify responses with reusable test cases.</p>{canManage && <Button onClick={() => setCreating(true)}>Create suite</Button>}</div> : <div className="automation-suite-grid">{suites.items.map((suite) => <article key={suite.id} className="automation-suite-card"><div className="panel-header"><AutomationBadge status={suite.status} /><small className="muted">{suite.auto_create_bugs ? "Automatic bugs on" : "Automatic bugs off"}</small></div><h3><Link to={`/projects/${projectId}/automation/suites/${suite.id}`}>{suite.name}</Link></h3><p className="muted">{suite.description || "No description"}</p><div className="automation-card-footer"><span>{environments.find((item) => item.id === suite.environment_id)?.name ?? "No environment"}</span><span>{suite.max_retries} retries</span></div></article>)}</div>}<AutomationPagination data={suites} onChange={setPage} /></section>
    <div className="automation-two-columns"><section className="panel"><h2>Failed run trend</h2>{statistics.failed_trends.length ? <div className="automation-trend" role="img" aria-label="Failed runs by date">{statistics.failed_trends.map((item) => <div key={item.date} title={`${item.date}: ${item.count} failed runs`}><strong>{item.count}</strong><div className="automation-trend-track"><span style={{ height: `${item.count / largestFailure * 100}%` }} /></div><small>{item.date.slice(5)}</small></div>)}</div> : <p className="empty-state">No failed runs recorded.</p>}</section><section className="panel"><div className="panel-header"><h2>Scheduled tests</h2><Link to={`/projects/${projectId}/automation/schedules`}>Manage schedules</Link></div>{schedules.length ? <ul className="automation-schedule-summary">{schedules.slice(0, 5).map((item) => <li key={item.id}><strong>{suites.items.find((suite) => suite.id === item.suite_id)?.name ?? item.suite_id.slice(0, 8)}</strong><span>{item.enabled ? "Enabled" : "Paused"} · <code>{item.cron_expression}</code> · {item.timezone}</span><small>Next: {item.next_run_at && item.enabled ? new Date(item.next_run_at).toLocaleString() : "Not scheduled"}</small></li>)}</ul> : <p className="empty-state">No schedules yet. Activate a suite to schedule it.</p>}</section></div>
    <section className="panel"><div className="panel-header"><h2>Recent failures</h2><Link to={`/projects/${projectId}/automation/runs?status=FAILED`}>View failures</Link></div><AutomationRunTable runs={statistics.recent_failures} projectId={projectId} suites={suites.items} /></section><section className="panel"><div className="panel-header"><h2>Recent runs</h2><Link to={`/projects/${projectId}/automation/runs`}>Filter run history</Link></div><AutomationRunTable runs={statistics.recent_runs} projectId={projectId} suites={suites.items} /></section>
  </>}{creating && <SuiteForm environments={environments} onSave={create} onClose={() => setCreating(false)} />}</AppLayout>;
}
