import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { allAutomationSuites, createAutomationSchedule, deleteAutomationSchedule, listAutomationSchedules, updateAutomationSchedule } from "../api/automation";
import { listApiEnvironments } from "../api/apiTesting";
import { extractErrorMessage } from "../api/client";
import { AutomationError, AutomationNav, AutomationPagination } from "../components/automation/AutomationShared";
import { ScheduleEditor } from "../components/automation/ScheduleEditor";
import { AppLayout } from "../components/layout/AppLayout";
import { Button } from "../components/ui/Button";
import { LoadingSpinner } from "../components/ui/LoadingSpinner";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import type { ApiEnvironment } from "../types/apiTesting";
import type { AutomationPage, AutomationSchedule, AutomationSuite, SchedulePayload } from "../types/automation";

export function AutomationSchedules() {
  const { projectId = "" } = useParams(); const { user } = useAuth(); const { showToast } = useToast();
  const [data, setData] = useState<AutomationPage<AutomationSchedule> | null>(null); const [suites, setSuites] = useState<AutomationSuite[]>([]); const [environments, setEnvironments] = useState<ApiEnvironment[]>([]); const [page, setPage] = useState(1); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<AutomationSchedule | "new" | null>(null);
  const canManage = user?.role === "ADMIN" || user?.role === "QA_ENGINEER";
  const load = useCallback(async () => { setError(""); setLoading(true); try { const [response, suiteResponse, envResponse] = await Promise.all([listAutomationSchedules(projectId, page), allAutomationSuites(projectId), listApiEnvironments(projectId)]); setData(response.data); setSuites(suiteResponse); setEnvironments(envResponse.data); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setLoading(false); } }, [projectId, page]);
  useEffect(() => { void load(); }, [load]);
  async function save(payload: SchedulePayload) { if (editing === "new") await createAutomationSchedule(projectId, payload); else if (editing) { const { suite_id: _suiteId, ...patch } = payload; await updateAutomationSchedule(editing.id, patch); } setEditing(null); showToast("Schedule saved.", "success"); await load(); }
  async function toggle(item: AutomationSchedule) { setBusy(true); try { await updateAutomationSchedule(item.id, { enabled: !item.enabled }); showToast(item.enabled ? "Schedule paused." : "Schedule enabled.", "success"); await load(); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setBusy(false); } }
  async function remove(item: AutomationSchedule) { if (!window.confirm("Delete this schedule? Existing run history will remain available.")) return; setBusy(true); try { await deleteAutomationSchedule(item.id); showToast("Schedule deleted.", "success"); await load(); } catch (reason) { setError(extractErrorMessage(reason)); } finally { setBusy(false); } }
  return <AppLayout><div className="page-header"><div><h1>Automation schedules</h1><p className="muted">Run active suites automatically in development, QA, and staging.</p></div>{canManage && <Button disabled={loading || busy} onClick={() => setEditing("new")}>Create schedule</Button>}</div><AutomationNav projectId={projectId} />{error && <AutomationError message={error} retry={load} />}<section className="panel">{loading ? <LoadingSpinner /> : data && <>{!data.items.length ? <div className="empty-state"><h2>No schedules yet</h2><p>Activate a suite, then choose a frequency and timezone.</p></div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Suite</th><th>Frequency</th><th>Environment</th><th>Next run</th><th>Last run</th><th>Status</th>{canManage && <th>Actions</th>}</tr></thead><tbody>{data.items.map((item) => { const suite = suites.find((value) => value.id === item.suite_id); return <tr key={item.id}><td><Link to={`/projects/${projectId}/automation/suites/${item.suite_id}`}>{suite?.name ?? item.suite_id.slice(0, 8)}</Link>{item.last_error && <p className="automation-schedule-error" role="status">{item.last_error}</p>}</td><td><code>{item.cron_expression}</code><small className="automation-table-secondary">{item.timezone}</small></td><td>{environments.find((env) => env.id === (item.environment_id || suite?.environment_id))?.name ?? "None"}</td><td>{item.next_run_at && item.enabled ? new Date(item.next_run_at).toLocaleString() : "—"}</td><td>{item.last_run_at ? new Date(item.last_run_at).toLocaleString() : "Never"}</td><td>{item.enabled ? "Enabled" : "Paused"}</td>{canManage && <td><div className="button-row"><Button variant="secondary" disabled={busy} onClick={() => void toggle(item)}>{item.enabled ? "Pause" : "Enable"}</Button><Button variant="ghost" disabled={busy} onClick={() => setEditing(item)}>Edit</Button><Button variant="ghost" disabled={busy} onClick={() => void remove(item)}>Delete</Button></div></td>}</tr>; })}</tbody></table></div>}<AutomationPagination data={data} onChange={setPage} /></>}</section>{editing && <ScheduleEditor initial={editing === "new" ? undefined : editing} suites={suites} environments={environments} onSave={save} onClose={() => setEditing(null)} />}</AppLayout>;
}
