import { useEffect, useState, type FormEvent } from "react";
import { useParams } from "react-router-dom";
import { createApiKey, createWebhook, deleteWebhook, listApiKeys, listDeliveries, listWebhooks, revokeApiKey } from "../api/operations";
import { AppLayout } from "../components/layout/AppLayout";
import { Button } from "../components/ui/Button";
import { useToast } from "../context/ToastContext";

const events = ["automation.run.started", "automation.run.completed", "automation.run.failed", "load_test.completed", "load_test.failed", "bug.created", "bug.updated"];
export function Integrations() {
  const { projectId = "" } = useParams(); const { showToast } = useToast();
  const [keys, setKeys] = useState<any[]>([]); const [hooks, setHooks] = useState<any[]>([]); const [deliveries, setDeliveries] = useState<any[]>([]); const [newToken, setNewToken] = useState("");
  const [keyName, setKeyName] = useState(""); const [hook, setHook] = useState({ name: "", url: "", secret: "", events: ["automation.run.failed", "load_test.failed"] });
  function refresh() { Promise.all([listApiKeys(projectId), listWebhooks(projectId), listDeliveries(projectId)]).then(([a,b,c]) => { setKeys(a.data); setHooks(b.data); setDeliveries(c.data); }).catch(() => showToast("Could not load integrations.", "error")); }
  useEffect(refresh, [projectId]);
  async function addKey(e: FormEvent) { e.preventDefault(); try { const r = await createApiKey(projectId, keyName); setNewToken(r.data.token); setKeyName(""); refresh(); } catch { showToast("API key could not be created.", "error"); } }
  async function addHook(e: FormEvent) { e.preventDefault(); try { await createWebhook(projectId, hook); setHook({ name: "", url: "", secret: "", events: ["automation.run.failed", "load_test.failed"] }); refresh(); } catch { showToast("Webhook could not be created. Use a public HTTPS URL and a 16+ character secret.", "error"); } }
  return <AppLayout><div className="page-header"><div><h1>CI/CD & Webhooks</h1><p className="muted">Project-scoped credentials and signed delivery endpoints.</p></div></div>
    {newToken && <div className="alert alert-success"><strong>Copy this key now; it will not be shown again:</strong><br/><code>{newToken}</code><Button variant="secondary" onClick={() => navigator.clipboard.writeText(newToken)}>Copy</Button></div>}
    <section className="panel"><h2>CI API keys</h2><form className="button-row" onSubmit={addKey}><label className="field"><span>Key name</span><input value={keyName} onChange={e => setKeyName(e.target.value)} required /></label><Button type="submit">Create key</Button></form>{keys.length === 0 ? <p className="muted">No CI API keys.</p> : <table className="table"><thead><tr><th>Name</th><th>Prefix</th><th>Last used</th><th/></tr></thead><tbody>{keys.map(row => <tr key={row.id}><td>{row.name}</td><td><code>{row.token_prefix}…</code></td><td>{row.last_used_at ? new Date(row.last_used_at).toLocaleString() : "Never"}</td><td><Button variant="danger" onClick={() => { if (confirm("Revoke this CI key?")) revokeApiKey(projectId, row.id).then(refresh); }}>Revoke</Button></td></tr>)}</tbody></table>}</section>
    <section className="panel"><h2>Webhooks</h2><form className="form-grid" onSubmit={addHook}><label className="field"><span>Name</span><input value={hook.name} onChange={e => setHook({...hook, name:e.target.value})} required /></label><label className="field"><span>HTTPS URL</span><input type="url" value={hook.url} onChange={e => setHook({...hook, url:e.target.value})} required /></label><label className="field"><span>Signing secret</span><input type="password" minLength={16} autoComplete="new-password" value={hook.secret} onChange={e => setHook({...hook, secret:e.target.value})} required /></label><fieldset><legend>Events</legend>{events.map(event => <label key={event}><input type="checkbox" checked={hook.events.includes(event)} onChange={e => setHook({...hook, events: e.target.checked ? [...hook.events,event] : hook.events.filter(x=>x!==event)})}/>{event}</label>)}</fieldset><div><Button type="submit">Add webhook</Button></div></form>{hooks.length === 0 ? <p className="muted">No webhooks configured.</p> : <table className="table"><thead><tr><th>Name</th><th>URL</th><th>Events</th><th/></tr></thead><tbody>{hooks.map(row => <tr key={row.id}><td>{row.name}</td><td>{row.url}</td><td>{row.events.length}</td><td><Button variant="danger" onClick={() => deleteWebhook(projectId,row.id).then(refresh)}>Delete</Button></td></tr>)}</tbody></table>}</section>
    <section className="panel"><h2>Recent deliveries</h2>{deliveries.length === 0 ? <p className="muted">No webhook deliveries.</p> : <table className="table"><thead><tr><th>Event</th><th>Status</th><th>Attempts</th><th>Last attempt</th><th>Reason</th></tr></thead><tbody>{deliveries.slice(0,20).map(row => <tr key={row.id}><td>{row.event}</td><td>{row.status}</td><td>{row.attempt_count}</td><td>{row.last_attempt_at ? new Date(row.last_attempt_at).toLocaleString() : "Pending"}</td><td>{row.failure_reason || "—"}</td></tr>)}</tbody></table>}</section>
  </AppLayout>;
}
