import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { compareLoadRuns, listLoadRuns } from "../api/loadTesting";
import { extractErrorMessage } from "../api/client";
import { AppLayout } from "../components/layout/AppLayout";
import { Button } from "../components/ui/Button";
import { useToast } from "../context/ToastContext";
import type { LoadComparison, LoadRun } from "../types/loadTesting";

export function LoadCompare() {
  const { projectId = "" } = useParams(); const { showToast } = useToast(); const [runs, setRuns] = useState<LoadRun[]>([]); const [runA, setRunA] = useState(""); const [runB, setRunB] = useState(""); const [comparison, setComparison] = useState<LoadComparison | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { listLoadRuns(projectId).then(({ data }) => { const complete = data.items.filter((item) => item.status === "COMPLETED"); setRuns(complete); setRunA(complete.find((item) => item.is_baseline)?.id ?? complete[1]?.id ?? ""); setRunB(complete[0]?.id ?? ""); }).catch((error) => showToast(extractErrorMessage(error), "error")); }, [projectId, showToast]);
  async function compare() { if (!runA || !runB || runA === runB) return; setBusy(true); try { setComparison((await compareLoadRuns(projectId, runA, runB)).data); } catch (error) { showToast(extractErrorMessage(error), "error"); } finally { setBusy(false); } }
  return <AppLayout><div className="page-header"><div><h1>Compare load-test runs</h1><p className="muted">Measure a candidate result against a baseline or previous execution.</p></div><Link to={`/projects/${projectId}/load-testing/runs`}>Run history</Link></div><section className="panel"><div className="comparison-picker"><label className="field"><span>Baseline / run A</span><select value={runA} onChange={(event) => setRunA(event.target.value)}><option value="">Select run</option>{runs.map((run) => <option value={run.id} key={run.id}>{run.run_key} · {run.load_test_name}{run.is_baseline ? " (baseline)" : ""}</option>)}</select></label><span>vs</span><label className="field"><span>Candidate / run B</span><select value={runB} onChange={(event) => setRunB(event.target.value)}><option value="">Select run</option>{runs.map((run) => <option value={run.id} key={run.id}>{run.run_key} · {run.load_test_name}</option>)}</select></label><Button isLoading={busy} disabled={!runA || !runB || runA === runB} onClick={compare}>Compare</Button></div></section>{comparison && <section className="panel"><h2>{comparison.run_a.run_key} vs {comparison.run_b.run_key}</h2><div className="table-wrap"><table className="data-table comparison-table"><thead><tr><th>Metric</th><th>Run A</th><th>Run B</th><th>Change</th></tr></thead><tbody>{comparison.metrics.map((item) => <tr key={item.metric}><td>{item.metric.replaceAll("_", " ")}</td><td>{item.run_a.toFixed(2)}</td><td>{item.run_b.toFixed(2)}</td><td className={item.difference > 0 ? "regression" : "improvement"}>{item.difference > 0 ? "+" : ""}{item.difference.toFixed(2)} {item.percent_change === null ? "" : `(${item.percent_change.toFixed(1)}%)`}</td></tr>)}</tbody></table></div></section>}</AppLayout>;
}
